export const basicOnb = [
  {
    "5 Jan": [
      {
        Task: "Basic setup & access  (Email id, Laptop, Slack, Figma, Platform, Lyearn, Monday board)",
        day: "1",
        type: "HR & Admin",
        Topic: "Welcome & Induction Day",
        Deadline: "5 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Induction Meet",
        day: "1",
        type: "Meeting",
        Topic: "Welcome & Induction Day",
        Deadline: "5 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "1-1 Connect with Reporting Managers",
        day: "1",
        type: "Meeting",
        Topic: "Welcome & Induction Day",
        Deadline: "5 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Leadership session",
        day: "1",
        type: "Meeting",
        Topic: "Welcome & Induction Day",
        Deadline: "5 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Policies & Compliance Course",
        day: "1",
        type: "Course",
        Topic: "Welcome & Induction Day",
        Deadline: "5 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Phishing awareness Course",
        day: "1",
        type: "Course",
        Topic: "Welcome & Induction Day",
        Deadline: "5 Jan",
        profile: "Engineering - Frontend",
      },
    ],
  },
  {
    "6 Jan": [
      {
        Task: "Refresher course - Basic Automation",
        day: "2",
        type: "Course",
        Topic: "Learning & enablement",
        Deadline: "6 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Refresher course - Basic Application",
        day: "2",
        type: "Course",
        Topic: "Learning & enablement",
        Deadline: "6 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Refresher course - Basic AI Agent",
        day: "2",
        type: "Course",
        Topic: "Learning & enablement",
        Deadline: "6 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Refresher course - Data platform",
        day: "2",
        type: "Course",
        Topic: "Learning & enablement",
        Deadline: "6 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Daily Check in",
        day: "2",
        type: "Documentation",
        Topic: "Learning & enablement",
        Deadline: "6 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Daily sync with RM",
        day: "2",
        type: "Meeting",
        Topic: "Learning & enablement",
        Deadline: "6 Jan",
        profile: "Engineering - Frontend",
      },
    ],
  },
  {
    "7 Jan": [
      {
        Task: "Basic Git",
        day: "3",
        type: "Course",
        Topic: "Learning & enablement",
        Deadline: "7 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Generic Doubt session",
        day: "3",
        type: "Meeting",
        Topic: "Learning & enablement",
        Deadline: "7 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Check in",
        day: "3",
        type: "Documentation",
        Topic: "Learning & enablement",
        Deadline: "7 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Daily sync with RM",
        day: "3",
        type: "Meeting",
        Topic: "Learning & enablement",
        Deadline: "7 Jan",
        profile: "Engineering - Frontend",
      },
    ],
  },
  {
    "8 Jan": [
      {
        Task: "Basic HTML",
        day: "4",
        type: "Course",
        Topic: "Learning & enablement",
        Deadline: "8 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Check in",
        day: "4",
        type: "Documentation",
        Topic: "Learning & enablement",
        Deadline: "8 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Daily sync with RM",
        day: "4",
        type: "Meeting",
        Topic: "Learning & enablement",
        Deadline: "8 Jan",
        profile: "Engineering - Frontend",
      },
    ],
  },
  {
    "9 Jan": [
      {
        Task: "Check in",
        day: "5",
        type: "Documentation",
        Topic: "Learning & enablement",
        Deadline: "9 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Daily sync with RM",
        day: "5",
        type: "Meeting",
        Topic: "Learning & enablement",
        Deadline: "9 Jan",
        profile: "Engineering - Frontend",
      },
    ],
  },
  {
    "10 Jan": [
      {
        Task: "Basic CSS",
        day: "5",
        type: "Course",
        Topic: "Learning & enablement",
        Deadline: "10 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Basic CSS",
        day: "6",
        type: "Course",
        Topic: "Learning & enablement",
        Deadline: "10 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Check in",
        day: "6",
        type: "Documentation",
        Topic: "Learning & enablement",
        Deadline: "10 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Daily sync with RM",
        day: "6",
        type: "Meeting",
        Topic: "Learning & enablement",
        Deadline: "10 Jan",
        profile: "Engineering - Frontend",
      },
    ],
  },
  {
    "11 Jan": [
      {
        Task: "How Browsers work",
        day: "7",
        type: "Course",
        Topic: "Learning & enablement",
        Deadline: "11 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Check in",
        day: "7",
        type: "Documentation",
        Topic: "Learning & enablement",
        Deadline: "11 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Daily sync with RM",
        day: "7",
        type: "Meeting",
        Topic: "Learning & enablement",
        Deadline: "11 Jan",
        profile: "Engineering - Frontend",
      },
    ],
  },
  {
    "12 Jan": [
      {
        Task: "Check in",
        day: "8",
        type: "Documentation",
        Topic: "Learning & enablement",
        Deadline: "12 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Daily sync with RM",
        day: "8",
        type: "Meeting",
        Topic: "Learning & enablement",
        Deadline: "12 Jan",
        profile: "Engineering - Frontend",
      },
    ],
  },
  {
    "13 Jan": [
      {
        Task: "Check in",
        day: "9",
        type: "Documentation",
        Topic: "Learning & enablement",
        Deadline: "13 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Daily sync with RM",
        day: "9",
        type: "Meeting",
        Topic: "Learning & enablement",
        Deadline: "13 Jan",
        profile: "Engineering - Frontend",
      },
    ],
  },
  {
    "14 Jan": [
      {
        Task: "Basic JS",
        day: "8",
        type: "Course",
        Topic: "Learning & enablement",
        Deadline: "14 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Basic JS",
        day: "9",
        type: "Course",
        Topic: "Learning & enablement",
        Deadline: "14 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Basic JS",
        day: "10",
        type: "Course",
        Topic: "Learning & enablement",
        Deadline: "14 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Check in",
        day: "10",
        type: "Documentation",
        Topic: "Learning & enablement",
        Deadline: "14 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Daily sync with RM",
        day: "10",
        type: "Meeting",
        Topic: "Learning & enablement",
        Deadline: "14 Jan",
        profile: "Engineering - Frontend",
      },
    ],
  },

  {
    "15 Jan": [
      {
        Task: "Check in",
        day: "11",
        type: "Documentation",
        Topic: "Learning & enablement",
        Deadline: "15 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Daily sync with RM",
        day: "11",
        type: "Meeting",
        Topic: "Learning & enablement",
        Deadline: "15 Jan",
        profile: "Engineering - Frontend",
      },
    ],
  },
  {
    "16 Jan": [
      {
        Task: "Check in",
        day: "12",
        type: "Documentation",
        Topic: "Learning & enablement",
        Deadline: "16 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Daily sync with RM",
        day: "12",
        type: "Meeting",
        Topic: "Learning & enablement",
        Deadline: "16 Jan",
        profile: "Engineering - Frontend",
      },
    ],
  },
  {
    "17 Jan": [
      {
        Task: "Check in",
        day: "13",
        type: "Documentation",
        Topic: "Learning & enablement",
        Deadline: "17 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Daily sync with RM",
        day: "13",
        type: "Meeting",
        Topic: "Learning & enablement",
        Deadline: "17 Jan",
        profile: "Engineering - Frontend",
      },
    ],
  },
  {
    "18 Jan": [
      {
        Task: "React",
        day: "11",
        type: "Course",
        Topic: "Learning & enablement",
        Deadline: "18 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "React",
        day: "12",
        type: "Course",
        Topic: "Learning & enablement",
        Deadline: "18 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "React",
        day: "13",
        type: "Course",
        Topic: "Learning & enablement",
        Deadline: "18 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "React",
        day: "14",
        type: "Course",
        Topic: "Learning & enablement",
        Deadline: "18 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Assignment",
        day: "14",
        type: "Assignment",
        Topic: "Learning & enablement",
        Deadline: "18 Jan",
        profile: "",
      },
      {
        Task: "Check in",
        day: "14",
        type: "Documentation",
        Topic: "Learning & enablement",
        Deadline: "18 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Daily sync with RM",
        day: "14",
        type: "Meeting",
        Topic: "Learning & enablement",
        Deadline: "18 Jan",
        profile: "Engineering - Frontend",
      },
    ],
  },
  {
    "19 Jan": [
      {
        Task: "Check in",
        day: "15",
        type: "Documentation",
        Topic: "Learning & enablement",
        Deadline: "19 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Daily sync with RM",
        day: "15",
        type: "Meeting",
        Topic: "Learning & enablement",
        Deadline: "19 Jan",
        profile: "Engineering - Frontend",
      },
    ],
  },
  {
    "20 Jan": [
      {
        Task: "TypeScript",
        day: "15",
        type: "Course",
        Topic: "Learning & enablement",
        Deadline: "20 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "TypeScript",
        day: "16",
        type: "Course",
        Topic: "Learning & enablement",
        Deadline: "20 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Check in",
        day: "16",
        type: "Documentation",
        Topic: "Learning & enablement",
        Deadline: "20 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Daily sync with RM",
        day: "16",
        type: "Meeting",
        Topic: "Learning & enablement",
        Deadline: "20 Jan",
        profile: "Engineering - Frontend",
      },
    ],
  },
  {
    "21 Jan": [
      {
        Task: "Clean Code",
        day: "17",
        type: "Course",
        Topic: "Learning & enablement",
        Deadline: "21 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Check in",
        day: "17",
        type: "Documentation",
        Topic: "Learning & enablement",
        Deadline: "21 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Daily sync with RM",
        day: "17",
        type: "Meeting",
        Topic: "Learning & enablement",
        Deadline: "21 Jan",
        profile: "Engineering - Frontend",
      },
    ],
  },
  {
    "22 Jan": [
      {
        Task: "RJSF",
        day: "18",
        type: "Course",
        Topic: "Learning & enablement",
        Deadline: "22 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Check in",
        day: "18",
        type: "Documentation",
        Topic: "Learning & enablement",
        Deadline: "22 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Daily sync with RM",
        day: "18",
        type: "Meeting",
        Topic: "Learning & enablement",
        Deadline: "22 Jan",
        profile: "Engineering - Frontend",
      },
    ],
  },
  {
    "23 Jan": [
      {
        Task: "React Query",
        day: "19",
        type: "Course",
        Topic: "Learning & enablement",
        Deadline: "23 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Check in",
        day: "19",
        type: "Documentation",
        Topic: "Learning & enablement",
        Deadline: "23 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Daily sync with RM",
        day: "19",
        type: "Meeting",
        Topic: "Learning & enablement",
        Deadline: "23 Jan",
        profile: "Engineering - Frontend",
      },
    ],
  },
  {
    "24 Jan": [
      {
        Task: "Check in",
        day: "20",
        type: "Documentation",
        Topic: "Learning & enablement",
        Deadline: "24 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Daily sync with RM",
        day: "20",
        type: "Meeting",
        Topic: "Learning & enablement",
        Deadline: "24 Jan",
        profile: "Engineering - Frontend",
      },
    ],
  },
  {
    "25 Jan": [
      {
        Task: "NextJS",
        day: "20",
        type: "Course",
        Topic: "Learning & enablement",
        Deadline: "25 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "NextJS",
        day: "21",
        type: "Course",
        Topic: "Learning & enablement",
        Deadline: "25 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Check in",
        day: "21",
        type: "Documentation",
        Topic: "Learning & enablement",
        Deadline: "25 Jan",
        profile: "Engineering - Frontend",
      },
      {
        Task: "Daily sync with RM",
        day: "21",
        type: "Meeting",
        Topic: "Learning & enablement",
        Deadline: "25 Jan",
        profile: "Engineering - Frontend",
      },
    ],
  },
];
